version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: csv_upload_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: csv_upload_dev
      MYSQL_USER: rails_user
      MYSQL_PASSWORD: rails_pass
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: